### PR TITLE
Added GitHub Actions and PKGBUILDS for swayfx and scenefx

### PR DESCRIPTION
**Pull request by ErikReider**

### CODE REVIEW

**Comment by ErikReider** [comment]
I'll push some enhancements to the actions tomorrow :)

**Comment by ErikReider** [comment]
Everything should be working now! All that's left is the Action Secrets :)

**Comment by WillPower3309** [comment]
Secrets added!

**Review by WillPower3309 — APPROVED** [review]

**Comment by WillPower3309** [comment]
Seems one test is failing though

**Comment by ErikReider** [comment]
> Seems one test is failing though

Due to scenefx not being available yet. Should be fixed after this is merged :)

**Pull request merged**
